### ISSUE TITLE
Unable to Access Database

### ISSUE THREAD

**Issue by cyramic** [SocialFinanceDigitalLabs/sfdata-platform#12]
Security Groups don't have correct ingress/egress rules set which is blocking connectivity.

**Comment by cyramic** [comment]
Will need to define a SecurityGroupIngress property as [defined here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#cfn-ec2-securitygroup-securitygroupingress)

Something like:
 ```
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Database Connectivity
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref DatabaseCIDRRange
```
